// src/common/constants/app.constants.ts
export const APP_CONSTANTS = {
  DEFAULT_PAGINATION_LIMIT: 10,
  MAX_PAGINATION_LIMIT: 100,
  PRICE_DECIMALS: 2,
  DISTANCE_UNIT: 'km',
  MINIMUM_ORDER_AMOUNT: 1,
  MAXIMUM_ORDER_AMOUNT: 1000,
  TOKEN_EXPIRY: '24h',
  LOCATION_PRECISION: 6
};
